### ISSUE TITLE
Failed to play livestream of twitch (patch included)

### ISSUE THREAD

**Issue by jeongminkim-islab** [23rd/TwitchPotPlayer#13]
After installing the latest version of TwitchPotPlayer, when I checked the list of Twitch broadcasts using the open url, I noticed that the playback address on the Url tab is parsing strangely.
Specifically, the streamer id after https://www.twitch.tv/ is displayed as the display name, so it could not be played at this address.
Unfortunately, the new twitch api does not provide the return value of the streamer's login id in the response field of the stream information.
So, after receiving user_id, we need to bypass this by requesting login id again.

The attachment is a new version of the "MediaUrlList - Twitch.as" file that I patched to do the above. The new GetLoginName () function has been added, and the code has been modified by calling GetChunkOfUsersOnline () function.
I hope the developers will apply this patch.

**Users who have not solved the playback problem can solve the problem by overwriting the existing "MediaUrlList-Twitch.as" file with the files contained in this compressed file.**

[MediaUrlList - Twitch.zip](https://github.com/23rd/TwitchPotPlayer/files/3706347/MediaUrlList.-.Twitch.zip)

**Comment by 23rd** [comment]
Hmm, thanks, I'll check it today. 
By the way, you can open a new pull request with your patch.

**Comment by jeongminkim-islab** [comment]
> Hmm, thanks, I'll check it today.
> By the way, you can open a new pull request with your patch.

Thanks for your fast response.
I'm not familiar with the github system yet, but I'll try it.
