### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by 0nomatopoeia** [23rd/TwitchPotPlayer#17]
No VODs or Streams will open as of last week (with the API change?)

Is there any way of debuging the problem on my end? ie some kind of verbose logging or such?
The youtube plugin still works fine in potplayer & streamlink passthrough to vlc also works
But i really miss the convenience & practicality of your plugin & having all my video on potplayer

Please help

Thanks

**Comment by 23rd** [comment]
Can you please provide any link of VOD or an error info?

**Comment by 0nomatopoeia** [comment]
**NO** VODs play, podplayer only says "Failed to start playback"
more info is blank

How can i get a detailed error log?

**Comment by 23rd** [comment]
Are you sure you have installed the latest version?

**Comment by 0nomatopoeia** [comment]
Yep, updated last week & yesterday again
I am still running potplayer 1.7.19955 though, as the new version dropped software HEVC support

**Comment by 23rd** [comment]
I dunno, you can open `MediaPlayParse - Twitch.as` file with notepad and remove two slashes `//` at the beginning of the line, save the file and play any VOD in the Potplayer. And then take screenshots of the output in the console.

https://github.com/23rd/TwitchPotPlayer/blob/0ed784727580730033baac4af25fda9ad0a47b3e/Media/PlayParse/MediaPlayParse%20-%20Twitch.as#L183

**Comment by 0nomatopoeia** [comment]
![twitch as](https://user-images.githubusercontent.com/27941617/67281996-8a27a000-f4c8-11e9-92d5-37c04a74c9d5.png)

**Comment by 0nomatopoeia** [comment]
It was working fine till the 9th, then on the 11th it no longer worked..

**Comment by 23rd** [comment]
I don't see any errors in your console output.
You can try some "old" version.
(Replace `MediaPlayParse - Twitch.as` file.)
[MediaPlayParse - Twitch.as.](https://github.com/23rd/TwitchPotPlayer/blob/d77a744151cbfda54187ef6935cc7118318edc40/Media/PlayParse/MediaPlayParse%20-%20Twitch.as)

**Comment by 0nomatopoeia** [comment]
Nope, still not working
i only updated it **after** it stopped working on the 11th anyway..

**Comment by 23rd** [comment]
Did you read this?

```
clientID= — takes clientID for API calls to the Twitch. It is highly recommended to get your own clientID on the Twitch and insert it here. If the value is empty, the default value is taken. If you insert an invalid value, the extension will not work.
```

**Comment by 0nomatopoeia** [comment]
I don't have a twitch account

**Comment by 23rd** [comment]
Check your antivirus, check your firewall.
Does my second "Url List" extension work?
What is your operating system?
Does the extension work on your friends' computers?
Does it work in a virtual machine?

**Comment by 0nomatopoeia** [comment]
disabled both, still nothing
url list also not working
my OS is 7 ultimate x64
Checked on two other machines, a windows 10 & a windows 7 home premium x64
Doesn't work on the windows 10 machine, does however work perfectly on the 7 home premium
all using the same router/connection
So evidently some change to my OS must be causing the problem, weird thing is that the youtube plugin still works fine & streamlink has no problem with twitch (MPV neither)
I also tried with a few diferent portable versions of potplayer (both 32bit & 64bit), still nothing
Dunno what else to try
¯\ _(ツ)_/¯

**Comment by 0nomatopoeia** [comment]
In any case the plugin is working fine
the problem is with potplayer itself, it won't even play direct links to the m3u8 on this machine
i wish there was a way to debug potplayer/get verbose logs
as it was working fine here & works fine on my other win7 machine

Thank you anyway, hopefully i'll fix it somehow

**Comment by 23rd** [comment]
>  it won't even play direct links to the m3u8 on this machine

Oops, seems like I forgot to ask about it from the beginning.

Maybe some codecs are broken.

**Comment by 0nomatopoeia** [comment]
Well, this is strange.. 
removing your plugin made it work
seems like potplayer is natively parsing the vod links now?

**Comment by 23rd** [comment]
I don't think so.
Anyway, it seems like there is a problem with your Potplayer instance, not with my extension, perhaps your instance have non-default paths or something like this.

**Comment by 23rd** [comment]
> seems like potplayer is natively parsing the vod (& stream) links now?

By the way, I asked Potplayer devs to support Twitch streams in 2015 and 2018. And both times, I've been refused.

**Comment by 0nomatopoeia** [comment]
well it's definitely working with no extension for me
¯\_(ツ)_/¯

also, they finally added vimeo to the youtube extension as well.. .

**Comment by 23rd** [comment]
Okay, what's version of your Potplayer?
Can you share files from your Extensions or Modules folder?

**Comment by 0nomatopoeia** [comment]
1.7.19955 64bit
It's a fresh install

**Comment by Spanden** [comment]
doesn't work
