### ISSUE TITLE
the live stream has a fix duration

### ISSUE THREAD

**Issue by Janaue** [23rd/TwitchPotPlayer#20]
I use potpalyer 200317 64-bit  on w10 1809 with your module. STOCK profile in PP.
So far it worked but now when i play a live video, eg by drag-drop or ctrl+U, the video has a fix duration and i need to click stop and play again to get new minutes of video. the video begins each time at the beginning.

ex: https://www.twitch.tv/videos/572670145?filter=all&sort=time
[ofc when you will see this message it will not be live] but the current schedule is here
https://www.chess.com/article/view/fide-candidates-tournament-2020

however, when i search for ''chess'' and then drag-drop the feed i want in PP, i get the live update
when i press ctrl++U PP says the playing URL is https://www.twitch.tv/gmbenjaminfinegold

**Comment by 23rd** [comment]
Yeah, that's how Twitch works.
If you open an unfinished VOD of any live stream in your browser, you will get exactly the same behavior.
