### ISSUE TITLE
Ability to have StreamDelay?

### ISSUE THREAD

**Issue by Mangos02** [23rd/TwitchPotPlayer#24]
is it possible to add the stream delay to the title or somewhere? so i know if im really far behind the actual stream, i just wanna know how far behind i am so i can fast forward a bit with faster playback and catch up.

also a catch up feature would be nice, to automatically slowly raise playback speed to reach a delay threshold of lets say 3 seconds or more depending on the setting i choose.

**Comment by 23rd** [comment]
This can't be done with extension API.

> so i know if im really far behind the actual stream

You can set up it in the settings of PotPlayer.
