### ISSUE TITLE
Twitch VODs appear to no longer work. Possibly an edge case due to a bad ISP.

### ISSUE THREAD

**Issue by BinToss** [23rd/TwitchPotPlayer#26]
Livestreams are working about as well as they do in a web-browser, but VODs don't work at all.

Internet Quality: piss poor. Rarely above 20mbps, but usually less than 3mbps. When combined with an average latency range of 600ms-6000ms, internet service is often slow and unreliable. Connections will drop constantly. Don't buy HughesNet.

[This VOD](https://www.twitch.tv/videos/853116267) streams as well as it can in a browser over inconsistent, frequently-throttled satellite internet and the same VOD fails to start streaming in PotPlayer.

TwitchPotPlayer can still resolve livestream and VOD URLs to stream info/title and as well as play livestreams.

This is while using my personal credentials in TPP's PlayParse and UrlList configs.

**Comment by 23rd** [comment]
Hmm, your link works fine in TwitchPotPlayer for me. Do you have another links that don't work?

**Comment by 23rd** [comment]
Okay, I have updated the play parse API, it should be better now.

**Comment by BinToss** [comment]
Sorry for the radio silence!
My DSL internet service is working again, so I've had the opportunity to
test over better internet. I can now get 4.2 mb/s DL rather than the
pre-wildfire 3.8 mb/s, so there's a positive of having had my entire
neighborhood on fire. The phone lines were replaced since they were all
either damaged or melted in the firestorm. No optical fiber, unfortunately.
Even the AT&T techs were disappointed they weren't installing optical fiber.

Live streams are working great and VODs are working just as well!
I haven't updated any plugins since my last report, **so the issue was
indeed a shoddy satellite internet service**. False alarm.

**Comment by BinToss** [comment]
Bad news.
VODs' URLs such as https://www.twitch.tv/videos/1096263340 fail nearly immediately via TwitchPotPlayer.
Media URLs (e.g. `https://usher.ttvnw.net/vod/1096263340.m3u8?{params}`) extracted by external software such as [Twitch To PotPlayer](https://addons.mozilla.org/en-US/firefox/addon/twitch-to-potplayer/) and SVP4's SVPTube extension (which leverages the youtube_dl library) still work.

```
1096263340.m3u8
?allow_source=true
&p=392406
&play_session_id=<PLAY_SESSION_ID>
&player_backend=mediaplayer
&playlist_include_framerate=<true/false>
&reassignments_supported=<true/false>
&sig=<char[40] SIG>
&supported_codecs=avc1
&token={
  "authorization":{"forbidden":false,"reason":""},
  "chansub":{ "restricted_bitrates":  [] },
  "device_id":<string DEVICE_ID>,
  "expires":1627410013,
  "https_required":true,
  "privileged":false,
  "user_id":<USER_ID>,
  "version":2,
  "vod_id":1096263340
}
&cdm=wv&
player_version=1.4.0
```
