### ISSUE TITLE
Ext still working?

### ISSUE THREAD

**Issue by DesweR** [23rd/TwitchPotPlayer#9]
I'm trying to play any Twitch video and I'm always getting "failed to start playback".

**Comment by 23rd** [comment]
Perhaps you open some popular streams?

**Comment by DesweR** [comment]
https://www.twitch.tv/blackufa
or
https://www.twitch.tv/videos/267745128

**Comment by 23rd** [comment]
>https://www.twitch.tv/videos/267745128

![image](https://user-images.githubusercontent.com/4051126/59204998-87c44980-8baa-11e9-977b-5c7682a2620a.png)

**Comment by DesweR** [comment]
does not work...

**Comment by 23rd** [comment]
@DesweR Are you sure you installed the extension correctly?

**Comment by DesweR** [comment]
Perhaps my token is incorrect?
![0](https://user-images.githubusercontent.com/1762304/59344849-0c44d280-8d39-11e9-99ba-3a27da6ccb33.PNG)
![1](https://user-images.githubusercontent.com/1762304/59344852-0cdd6900-8d39-11e9-8a76-dc589caf7844.PNG)
![2](https://user-images.githubusercontent.com/1762304/59344853-0cdd6900-8d39-11e9-9170-7d9d93d392fa.PNG)
![3](https://user-images.githubusercontent.com/1762304/59344854-0d75ff80-8d39-11e9-9db1-0bae5ced8809.PNG)
![4](https://user-images.githubusercontent.com/1762304/59344855-0e0e9600-8d39-11e9-9a01-e7e8cf66b7a4.PNG)
![5](https://user-images.githubusercontent.com/1762304/59344856-0e0e9600-8d39-11e9-9d7e-45e8a3678176.PNG)
![6](https://user-images.githubusercontent.com/1762304/59344858-0ea72c80-8d39-11e9-8dc9-967903003258.PNG)
![7](https://user-images.githubusercontent.com/1762304/59344859-0ea72c80-8d39-11e9-88e3-86ef1b4ead81.PNG)

**Comment by 23rd** [comment]
Try to remove values of `clientID` and `oauthToken`.

```
clientID=
oauthToken=
```

**Comment by DesweR** [comment]
Does not work.

**Comment by 23rd** [comment]
Honestly, I don't know how to help you. My friends and I have been using the extension for a year.

**Comment by DesweR** [comment]
I found out that the extension does not work on Windows XP, but it works on Windows 7.

**Comment by 23rd** [comment]
Do YouTube urls in Potplayer work for Windows XP?

**Comment by DesweR** [comment]
Yes

**Comment by U1s2e3r4n5a6m7e** [comment]
This extension only grab the title but streams or VODs don't start **right now**. This is my 2nd encounter with this issue. The problem was solved by itself after 2-12 hours **in the previous one**.
Am I the only one having issue? Can someone check it? @23rd

**Comment by Tororu** [comment]
@U1s2e3r4n5a6m7e 
Not working here either. Having the exact same problem DesweR had. Worked fine yesterday

**Comment by 23rd** [comment]
@U1s2e3r4n5a6m7e @Tororu 
Seems like the previous default Client-ID is broken.
Can you check it with the latest changes?

**Comment by U1s2e3r4n5a6m7e** [comment]
> 
> 
> @U1s2e3r4n5a6m7e @Tororu
> Seems like the previous default Client-ID is broken.
> Can you check it with the latest changes?

Works like a charm again. Thank you so much : )

**Comment by Tororu** [comment]
> @U1s2e3r4n5a6m7e @Tororu
> Seems like the previous default Client-ID is broken.
> Can you check it with the latest changes?

Yep works again. Thanks!

**Comment by 23rd** [comment]
I think I should close this issue.

It works fine for Win7+ and does not work for WinXP.
And I think I can do nothing to make it works for WinXP.
